---
- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg2
    state: present

- name: Prepare apt keyring directory.
  ansible.builtin.file:
    path: "{{ docker_apt_keyring_file | dirname }}"
    state: directory
    mode: 0755

- name: Add Docker apt key.
  ansible.builtin.get_url:
    url: "{{ docker_apt_gpg_key }}"
    dest: "{{ docker_apt_keyring_file }}"
    mode: '0644'
    force: true

- name: Be sure deprecated Docker repository is absent.
  file: 
    path: "/etc/apt/sources.list.d/download_docker_com_linux_ubuntu.list"
    state: absent

- name: Add Docker repository.
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    filename: docker.list
    state: present
    update_cache: true